### ISSUE TITLE
Update URL in Mutual practice exam

### ISSUE THREAD

**Issue by Insectslayer** [teaching-lab/stack-cs-activities#32]
The "Creating quiz questions" URLs seem to be outdated in this document: [Mutual practice exam](https://github.com/teaching-lab/stack-cs-activities/tree/master/activities/mutual-practice-exam).

**Comment by valdemarsv** [comment]
Thank you, fixed in the commit c6ac2825e4f534a3256466e0e5145ec7260d8485
